services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: erbium-cloudflared
    secrets:
      - tunnel_token
    command: >
      tunnel run --token $$(cat /run/secrets/tunnel_token)
    restart: unless-stopped
secrets:
  tunnel_token:
    file: ./cloudflared_tunnel_token.txt