services:
  SERVICE_NAME:
    image: nvidia/cuda:13.0.0-devel-ubuntu24.04
    hostname: erbium
    container_name: erbium
    network_mode: labnet
    volumes:
      - ./motd:/etc/motd:ro
      - ./venv.sh:/etc/profile.d/venv.sh:ro
      - ./monitor.cpp:/workspace/monitor.cpp:ro
      - S:/erbium_input:/workspace/input:ro
      - S:/erbium_output:/workspace/output
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: >
      bash -lc '
              set -e
              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl git gnupg openssh-server python3.12 python3.12-venv
              mkdir -p /var/run/sshd /workspace
              python3.12 -m venv /workspace/venv
              echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
              echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
              /usr/sbin/sshd -D
            '
    restart: unless-stopped