services:
  SERVICE_NAME:
    image: nvidia/cuda:13.0.0-devel-ubuntu24.04
    hostname: erbium
    container_name: erbium
    networks: [labnet]
    volumes:
      - ./motd:/etc/motd:ro
      - ./venv.sh:/etc/profile.d/venv.sh:ro
      - ./backup-output.sh:/usr/local/bin/backup-output.sh:ro
      - S:/erbium_input:/workspace/input:ro
      - S:/erbium_output:/workspace/output
      - S:/erbium_backup:/workspace/backup
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      BORG_REPO: /workspace/backup
    command: >
      bash -lc '
              set -e
              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl unzip zip wget git gnupg openssh-server python3.12 python3.12-venv tmux vim borgbackup
              mkdir -p /var/run/sshd /workspace/app /workspace/venv
              id -u access >/dev/null 2>&1 || useradd -m -s /bin/bash access
              echo "access:sshpassword" | chpasswd
              groupadd -f video
              groupadd -f render
              usermod -aG video,render access || true
              chown -R access:access /workspace/app /workspace/output /workspace/venv
              su - access -c "python3.12 -m venv /workspace/venv"
              su - access -c "/workspace/venv/bin/pip install torch torchvision jupyterlab git+https://github.com/ProjectNeura/Erbium"
              chown root:root /workspace/backup
              chmod 700 /workspace/backup
              if [ ! -f /workspace/backup/config ]; then
                borg init --encryption=none /workspace/backup
              fi
              (
                while true; do
                /usr/local/bin/backup-output.sh || true
                sleep 43200
                done
              ) &
              echo "PermitRootLogin no" >> /etc/ssh/sshd_config
              echo "PubkeyAuthentication no" >> /etc/ssh/sshd_config
              echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
              echo "AllowUsers access" >> /etc/ssh/sshd_config
              /usr/sbin/sshd
              su - access -c "/workspace/venv/bin/jupyter lab --no-browser --port=8080 --ip=0.0.0.0 --ServerApp.root_dir=/workspace --ServerApp.trust_xheaders=True --ServerApp.allow_remote_access=True" &
              /workspace/venv/bin/python -m erbium server run -p 8000
            '
    restart: unless-stopped
networks:
  labnet:
    external: true