services:
  SERVICE_NAME:
    image: nvidia/cuda:13.0.0-devel-ubuntu24.04
    hostname: erbium
    container_name: erbium
    networks: [labnet]
    volumes:
      - ./motd:/etc/motd:ro
      - ./venv.sh:/etc/profile.d/venv.sh:ro
      - S:/erbium_input:/workspace/input:ro
      - S:/erbium_output:/workspace/output
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: >
      bash -lc '
              set -e
              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl git gnupg openssh-server python3.12 python3.12-venv tmux vim
              mkdir -p /var/run/sshd /workspace/app
              id -u access >/dev/null 2>&1 || useradd -m -s /bin/bash access
              echo "access:sshpassword" | chpasswd
              chown -R access:access /workspace/app
              chown -R access:access /workspace/output
              python3.12 -m venv /workspace/venv
              /workspace/venv/bin/pip install torch torchvision jupyterlab
              echo "PermitRootLogin no" >> /etc/ssh/sshd_config
              echo "PubkeyAuthentication no" >> /etc/ssh/sshd_config
              echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
              echo "AllowUsers access" >> /etc/ssh/sshd_config
              /usr/sbin/sshd
              su - access -c "/workspace/venv/bin/jupyter lab --no-browser --port=8080 --ip=0.0.0.0 --ServerApp.root_dir=/workspace --ServerApp.trust_xheaders=True --ServerApp.allow_remote_access=True" &
              /workspace/venv/bin/pip git+https://github.com/ProjectNeura/Erbium
              /workspace/venv/bin/python -m erbium server run -p 8000
            '
    restart: unless-stopped
networks:
  labnet:
    external: true